apiVersion: apps/v1
kind: Deployment
metadata:
  name: morze-5000
spec:
  selector:
    matchLabels:
      app: morze
  replicas: 2
  template:
    metadata:
      labels:
        app: morze
    spec:
      containers:
      - name: morze
        image: "gcr.io/practical-scion-165616/morze:latest"
